# Generated by Django 3.2.4 on 2021-06-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('duration', models.IntegerField()),
                ('genre', models.CharField(max_length=64)),
            ],
        ),
    ]
