# Generated by Django 3.2.4 on 2021-06-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundify', '0003_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='contacto_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
