# Generated by Django 3.2.4 on 2021-07-02 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soundify', '0004_contacto_contacto_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta1', models.CharField(max_length=32)),
                ('resposta2', models.CharField(max_length=32)),
                ('resposta3', models.CharField(max_length=32)),
                ('resposta4', models.CharField(max_length=32)),
                ('resposta5', models.CharField(max_length=32)),
                ('resposta6', models.CharField(max_length=32)),
                ('resposta7', models.CharField(max_length=32)),
                ('resposta8', models.CharField(max_length=32)),
                ('resposta9', models.CharField(max_length=32)),
                ('resposta10', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soundify.user')),
            ],
        ),
    ]
