# Generated by Django 3.2.4 on 2021-07-02 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soundify', '0005_quizz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='resposta1',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='resposta10',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='resposta2',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='resposta3',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='resposta4',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='resposta5',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='resposta6',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='resposta7',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='resposta8',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='resposta9',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soundify.user'),
        ),
    ]
